stages:
  - build
  - test
  - push
  - deploy

variables:
  REGISTRY: registry.gitflic.ru
  IMAGE_NAME: ${CI_PROJECT_PATH}/ml_service
  TAG: latest

# ------------------------------
# СБОРКА DOCKER ОБРАЗА
# ------------------------------
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "===> Building docker image"
    - docker build -t $REGISTRY/$IMAGE_NAME:$TAG .
  artifacts:
    expire_in: 1 week
    paths:
      - .

# ------------------------------
# ЗАПУСК ТЕСТОВ
# ------------------------------
test:
  stage: test
  image: python:3.12-slim
  before_script:
    - pip install --no-cache-dir -r requirements.txt
  script:
    - echo "===> Running tests"
    - bash tests/test_service.sh

# ------------------------------
# PUSH В REGISTRY GITFLIC
# ------------------------------
push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $REGISTRY -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t $REGISTRY/$IMAGE_NAME:$TAG .
    - docker push $REGISTRY/$IMAGE_NAME:$TAG

# ------------------------------
# SSH ДЕПЛОЙ НА ВИРТУАЛКУ
# ------------------------------
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client bash sshpass
  script:
    - echo "===> DEPLOY to server"
    - sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        cd $Project_DIR && \
        git pull && \
        docker login $REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD && \
        docker-compose pull && \
        docker-compose up -d --remove-orphans
      "
  only:
    - main
