#image: python:3.12-slim


stages:
  - lint
  - test
  - train
  - build
  - integration
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip


lint:
  stage: lint
  before_script:
    - python3 -m venv .venv
    - .venv/bin/pip install --upgrade pip --quiet
    - .venv/bin/pip install -q ruff mypy
  script:
    - .venv/bin/ruff check src/ tests/ --fix
  allow_failure: false
  only:
    - main


test_smoke:
  stage: test
  needs: 
    - lint
  before_script:
    - python3 -m venv .venv
    - .venv/bin/pip install --upgrade pip
    - .venv/bin/pip install -r requirements.txt pytest
    - export PYTHONPATH="$CI_PROJECT_DIR"
  script:
    - .venv/bin/pytest -q tests/test_api_sanity.py
  only:
    - main


unit_tests:
  stage: test
  needs:
    - test_smoke   
  before_script:
    - python3 -m venv .venv
    - .venv/bin/pip install --upgrade pip --quiet
    - .venv/bin/pip install -q -r requirements.txt pytest
    - export PYTHONPATH="$CI_PROJECT_DIR"
  script:
    - .venv/bin/pytest -q tests/test_taxi.py
  only:
    - main


train_model:
  stage: train
  needs: 
    - unit_tests 
  before_script:
    - python3 -m venv .venv
    - .venv/bin/pip install --upgrade pip --quiet
    - .venv/bin/pip install -q -r requirements.txt
  script:
    - >
      .venv/bin/python src/service/train_and_save_model.py
      --csv src/uber.csv
      --output src/service/model.pkl
      --test-size 0.2
      --random-state 42
  artifacts:
    when: always
    paths:
      - src/service/model.pkl
      - metrics/train_metrics.json
  only:
    - main


build_and_push:
  stage: build
  needs:
    - train_model
 # before_script:
  #  - apt-get update
   # - apt-get install -y docker.io
 # image: docker:26.0.5-dind  # изменено: используем docker:dind для доступа к Docker
  #services:
 #   - docker:26.0.5-dind  # изменено: включаем docker daemon в контейнере
 # variables:
 #   DOCKER_HOST: tcp://docker:2375  # изменено: подключаемся к Docker daemon
 #   DOCKER_TLS_CERTDIR: ""          # изменено: выключаем TLS для простоты
  script:
    #- echo "Docker installed:"
   # - docker --version
  
    - echo "Logging into registry..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitflic.ru

    - echo "Building image..."
    - docker build -t "$IMAGE_NAME:$CI_COMMIT_SHA" .

    - echo "Pushing..."
    - docker push "$IMAGE_NAME:$CI_COMMIT_SHA"

  only:
    - main



integration_tests:
  stage: integration
  needs: 
    - build_and_push
  before_script:
    - python3 -m venv .venv
    - .venv/bin/pip install -U pip
    - .venv/bin/pip install pytest requests

  script:
    - docker pull "$IMAGE_NAME:$CI_COMMIT_SHA" 
    - docker run -d --name api-test -p 32000:32000 "$IMAGE_NAME:$CI_COMMIT_SHA"
    - sleep 7

    - echo "=== docker ps -a ==="
    - docker ps -a || true
    - echo "=== docker logs api-test ==="
    - docker logs api-test || true
    - .venv/bin/pytest -q tests/test_endpoints.py
  after_script:
    - docker stop api-test 
    - docker rm -f api-test 
  only:
    - main

deploy:
  stage: deploy
  needs:
    - build_and_push

  script:
    # переносим ключ из CI
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

    # синк репозитория
    - rsync -az --exclude 'nginx/conf.d/upstream.conf' 
      -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" 
      ./ "$DEPLOY_USER@$DEPLOY_HOST:/opt/uber/"


    # запускаем deploy.sh
    - ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "
        cd /opt/uber &&
        chmod +x scripts/deploy.sh &&
        ./scripts/deploy.sh \"$CI_COMMIT_SHA\"
      "
  only:
    - main