stages:
  - test
  - build

test:
  stage: test
  image: python:3.12
  script:
    - pip install -r requirements.txt
    - python src/service/train_and_save_model.py
    - pytest tests/ -v

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t taxi-app .
  only:
    - main
